import { db } from "@workspace/db";
import { exercisesTable } from "@workspace/db";
import { sql } from "drizzle-orm";

const exercises = [
  { name: "TRX Squat", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "TRX Rows", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: true, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "TRX Bicep Curls", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "TRX Chest Press", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: true, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "TRX Tricep Extension", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "TRX Plank", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: true, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "TRX Lunge", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "TRX Shoulder Press", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: false, hitShoulder: true, classification: "Functional/Dynamic" },
  { name: "Machine Leg Press", equipment: "Full Gym", difficulty: "Beginner", isCompound: true, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Bench Press", equipment: "Full Gym", difficulty: "Beginner", isCompound: true, hitChest: true, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Incline Bench Press", equipment: "Full Gym", difficulty: "Beginner", isCompound: true, hitChest: true, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: true, classification: "Strength" },
  { name: "Barbell Row", equipment: "Full Gym", difficulty: "Intermediate", isCompound: true, hitChest: false, hitBack: true, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Deadlift", equipment: "Full Gym", difficulty: "Advanced", isCompound: true, hitChest: false, hitBack: true, hitLegs: true, hitCore: true, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Squat", equipment: "Full Gym", difficulty: "Intermediate", isCompound: true, hitChest: false, hitBack: false, hitLegs: true, hitCore: true, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Overhead Press", equipment: "Full Gym", difficulty: "Intermediate", isCompound: true, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: true, classification: "Strength" },
  { name: "Pull-Up", equipment: "Full Gym", difficulty: "Intermediate", isCompound: true, hitChest: false, hitBack: true, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Push-Up", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: true, hitBack: false, hitLegs: false, hitCore: true, hitArm: true, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Bodyweight Squat", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Lunge", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Plank", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: true, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Mountain Climbers", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: true, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Burpee", equipment: "Bodyweight", difficulty: "Intermediate", isCompound: true, hitChest: true, hitBack: false, hitLegs: true, hitCore: true, hitArm: true, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Tricep Dips", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: true, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Pike Push-Up", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: true, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: true, classification: "Functional/Dynamic" },
  { name: "Superman", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: true, hitLegs: false, hitCore: true, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Glute Bridge", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: true, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Side Plank", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: true, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Crunches", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: true, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Leg Raises", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: true, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Jump Squat", equipment: "Bodyweight", difficulty: "Intermediate", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Incline Push-Up", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: true, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Decline Push-Up", equipment: "Bodyweight", difficulty: "Intermediate", isCompound: false, hitChest: true, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: true, classification: "Functional/Dynamic" },
  { name: "Diamond Push-Up", equipment: "Bodyweight", difficulty: "Intermediate", isCompound: false, hitChest: true, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Bicycle Crunches", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: true, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Step-Ups", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Wall Sit", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Jumping Jacks", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: true, classification: "Functional/Dynamic" },
  { name: "High Knees", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: true, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Dumbbell Chest Press", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: true, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Dumbbell Incline Press", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: true, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: true, classification: "Strength" },
  { name: "Dumbbell Fly", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: true, hitBack: false, hitLegs: false, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Dumbbell Row", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: true, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Dumbbell Bicep Curl", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Hammer Curl", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Dumbbell Shoulder Press", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: true, classification: "Strength" },
  { name: "Lateral Raise", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: false, hitShoulder: true, classification: "Strength" },
  { name: "Front Raise", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: false, hitShoulder: true, classification: "Strength" },
  { name: "Rear Delt Fly", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: true, hitLegs: false, hitCore: false, hitArm: false, hitShoulder: true, classification: "Strength" },
  { name: "Dumbbell Tricep Kickback", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Dumbbell Overhead Tricep Extension", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Dumbbell Goblet Squat", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: true, hitChest: false, hitBack: false, hitLegs: true, hitCore: true, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Dumbbell Romanian Deadlift", equipment: "Dumbbells only", difficulty: "Intermediate", isCompound: true, hitChest: false, hitBack: true, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Dumbbell Lunge", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Dumbbell Step-Up", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Dumbbell Sumo Squat", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Dumbbell Calf Raise", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Dumbbell Russian Twist", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: true, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Chest Cable Fly", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: true, hitBack: false, hitLegs: false, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Cable Row", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: true, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Lat Pulldown", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: true, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Cable Tricep Pushdown", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Cable Bicep Curl", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Pec Deck Machine", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: true, hitBack: false, hitLegs: false, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Machine Shoulder Press", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: true, classification: "Strength" },
  { name: "Machine Row", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: true, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Leg Extension", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Leg Curl", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Calf Raise Machine", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Hip Abductor Machine", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Hip Adductor Machine", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Preacher Curl", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Close Grip Bench Press", equipment: "Full Gym", difficulty: "Intermediate", isCompound: false, hitChest: true, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Arnold Press", equipment: "Dumbbells only", difficulty: "Intermediate", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: true, classification: "Strength" },
  { name: "Concentration Curl", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Incline Dumbbell Curl", equipment: "Dumbbells only", difficulty: "Intermediate", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Dumbbell Pullover", equipment: "Dumbbells only", difficulty: "Intermediate", isCompound: false, hitChest: true, hitBack: true, hitLegs: false, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Single-Arm Dumbbell Row", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: true, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Dumbbell Deadlift", equipment: "Dumbbells only", difficulty: "Intermediate", isCompound: true, hitChest: false, hitBack: true, hitLegs: true, hitCore: true, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Cable Face Pull", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: true, hitLegs: false, hitCore: false, hitArm: false, hitShoulder: true, classification: "Strength" },
  { name: "Upright Row", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: true, classification: "Strength" },
  { name: "Shrugs", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: true, hitLegs: false, hitCore: false, hitArm: false, hitShoulder: true, classification: "Strength" },
  { name: "Bent Over Lateral Raise", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: false, hitShoulder: true, classification: "Strength" },
  { name: "Spider Curl", equipment: "Full Gym", difficulty: "Intermediate", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Skull Crusher", equipment: "Full Gym", difficulty: "Intermediate", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Hip Thrust", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Bulgarian Split Squat", equipment: "Dumbbells only", difficulty: "Intermediate", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Nordic Curl", equipment: "Bodyweight", difficulty: "Advanced", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Pistol Squat", equipment: "Bodyweight", difficulty: "Advanced", isCompound: true, hitChest: false, hitBack: false, hitLegs: true, hitCore: true, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Handstand Push-Up", equipment: "Bodyweight", difficulty: "Advanced", isCompound: false, hitChest: true, hitBack: false, hitLegs: false, hitCore: true, hitArm: true, hitShoulder: true, classification: "Functional/Dynamic" },
  { name: "L-Sit", equipment: "Bodyweight", difficulty: "Advanced", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: true, hitArm: true, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Weighted Pull-Up", equipment: "Full Gym", difficulty: "Advanced", isCompound: true, hitChest: false, hitBack: true, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Dips", equipment: "Full Gym", difficulty: "Intermediate", isCompound: false, hitChest: true, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Cable Overhead Tricep Extension", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Straight Arm Pulldown", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: true, hitLegs: false, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Reverse Fly Machine", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: false, hitShoulder: true, classification: "Strength" },
  { name: "Serratus Crunch", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: true, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Ab Wheel Rollout", equipment: "Full Gym", difficulty: "Intermediate", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: true, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Hanging Leg Raise", equipment: "Full Gym", difficulty: "Intermediate", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: true, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Cable Woodchop", equipment: "Full Gym", difficulty: "Intermediate", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: true, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Barbell Hip Thrust", equipment: "Full Gym", difficulty: "Intermediate", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: true, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Hack Squat Machine", equipment: "Full Gym", difficulty: "Intermediate", isCompound: true, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Seated Leg Curl", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Glute Kickback Machine", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Seated Calf Raise", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Reverse Curl", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Wrist Curl", equipment: "Dumbbells only", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Box Jump", equipment: "Full Gym", difficulty: "Intermediate", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Kettlebell Swing", equipment: "Full Gym", difficulty: "Intermediate", isCompound: true, hitChest: false, hitBack: true, hitLegs: true, hitCore: true, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Barbell Curl", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "EZ Bar Curl", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Tricep Rope Pushdown", equipment: "Full Gym", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: false, hitArm: true, hitShoulder: false, classification: "Strength" },
  { name: "Standing Oblique Crunch", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: true, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Donkey Kick", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Fire Hydrant", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: false, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Bear Crawl", equipment: "Bodyweight", difficulty: "Intermediate", isCompound: false, hitChest: true, hitBack: false, hitLegs: true, hitCore: true, hitArm: false, hitShoulder: true, classification: "Functional/Dynamic" },
  { name: "Inchworm", equipment: "Bodyweight", difficulty: "Beginner", isCompound: false, hitChest: false, hitBack: false, hitLegs: true, hitCore: true, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "V-Up", equipment: "Bodyweight", difficulty: "Intermediate", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: true, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Hollow Body Hold", equipment: "Bodyweight", difficulty: "Intermediate", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: true, hitArm: false, hitShoulder: false, classification: "Functional/Dynamic" },
  { name: "Dragon Flag", equipment: "Bodyweight", difficulty: "Advanced", isCompound: false, hitChest: false, hitBack: false, hitLegs: false, hitCore: true, hitArm: false, hitShoulder: false, classification: "Strength" },
  { name: "Plyometric Push-Up", equipment: "Bodyweight", difficulty: "Advanced", isCompound: false, hitChest: true, hitBack: false, hitLegs: false, hitCore: true, hitArm: true, hitShoulder: false, classification: "Functional/Dynamic" },
];

async function main() {
  console.log("Seeding exercises...");

  const existing = await db.select({ id: exercisesTable.id }).from(exercisesTable).limit(1);
  if (existing.length > 0) {
    console.log("Exercises already seeded, skipping.");
    process.exit(0);
  }

  await db.insert(exercisesTable).values(exercises);
  console.log(`Seeded ${exercises.length} exercises successfully!`);
  process.exit(0);
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
